version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - elt-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dumball:tammu123@db:5432/accha
      - DEBUG_MODE=true
      - UPLOAD_DIR=/app/uploads
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
      - ./backend/logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - elt-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=dumball
      - POSTGRES_PASSWORD=tammu123
      - POSTGRES_DB=accha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - elt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dumball -d accha"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  elt-network:
    driver: bridge
